### ISSUE TITLE
pkNX issue

### ISSUE THREAD

**Issue by tkdfredrik04** [kwsch/pkNX#100]
Everytime i try to luanch pkNX with my dump an error message pops up. Ive tried to create multiple more dumps but it doesnt seem to change. 

Here is the error
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at pkNX.Structures.PersonalTable.SplitBytes(Byte[] data, Int32 size)
   at pkNX.Structures.PersonalTable..ctor(Byte[] data, GameVersion format)
   at pkNX.Game.GameManagerSWSH.Initialize()
   at pkNX.Game.GameManager..ctor(GameLocation rom, Int32 language)
   at pkNX.Game.GameManagerSWSH..ctor(GameLocation rom, Int32 language)
   at pkNX.Game.GameManager.GetManager(GameLocation loc, Int32 language)
   at pkNX.WinForms.Controls.EditorBase.GetEditor(String loc, Int32 language) in C:\Users\fresk\source\repos\pkNX\heftig saker\pkNX.WinForms\MainEditor\EditorProvider.cs:line 63
   at pkNX.WinForms.Main.OpenFolder(String path) in C:\Users\fresk\source\repos\pkNX\heftig saker\pkNX.WinForms\Main.cs:line 129
   at pkNX.WinForms.Main.OpenPath(String path) in C:\Users\fresk\source\repos\pkNX\heftig saker\pkNX.WinForms\Main.cs:line 109
   at pkNX.WinForms.Main.Menu_Open_Click(Object sender, EventArgs e) in C:\Users\fresk\source\repos\pkNX\heftig saker\pkNX.WinForms\Main.cs:line 62
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
pkNX
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/fresk/source/repos/pkNX/heftig%20saker/pkNX.WinForms/bin/Debug/pkNX.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
pkNX.Structures
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/fresk/source/repos/pkNX/heftig%20saker/pkNX.WinForms/bin/Debug/pkNX.exe
----------------------------------------
pkNX.Game
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/fresk/source/repos/pkNX/heftig%20saker/pkNX.WinForms/bin/Debug/pkNX.exe
----------------------------------------
pkNX.Containers
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/fresk/source/repos/pkNX/heftig%20saker/pkNX.WinForms/bin/Debug/pkNX.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by sora10pls** [comment]
#85 
#90 
#99
