### ISSUE TITLE
Trying to randomzie the pokemons in the wild on pokemon let's go Eevee

### ISSUE THREAD

**Issue by TaskManager06** [kwsch/pkNX#167]
Everytime I press the wild/ShinyRate/Tm/TypeChart/shop 1 and 2 I just get this error message. I dumped the games with nxdumptool and tried with and without updates but none works. I dont know if this is the right place to ask and if it is wrong I will take it down.

````
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'FlatSharp.RoslynSerializerGenerator' threw an exception. ---> System.ArgumentException: Empty path name is not legal.
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Roslyn.Utilities.FileUtilities.OpenFileStream(String path)
   at Microsoft.CodeAnalysis.MetadataReference.CreateFromFile(String path, MetadataReferenceProperties properties, DocumentationProvider documentation)
   at FlatSharp.RoslynSerializerGenerator..cctor()
   --- End of inner exception stack trace ---
   at FlatSharp.RoslynSerializerGenerator..ctor(FlatBufferSerializerOptions options, TypeModelContainer typeModelContainer)
   at FlatSharp.FlatBufferSerializer.GetOrCreateTypedSerializer[TRoot]()
   at pkNX.WinForms.Controls.EditorGG.PopWildEdit(GameFile type)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at pkNX.WinForms.Controls.EditorBase.<>c__DisplayClass12_0.<GetControls>b__0(Object s, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
pkNX
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/leoun/Downloads/pkNX-master/pkNX-master/pkNX.WinForms/bin/Release/net461/pkNX.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
pkNX.Structures.FlatBuffers
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/leoun/Downloads/pkNX-master/pkNX-master/pkNX.WinForms/bin/Release/net461/pkNX.exe
----------------------------------------
pkNX.Structures
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/leoun/Downloads/pkNX-master/pkNX-master/pkNX.WinForms/bin/Release/net461/pkNX.exe
----------------------------------------
System.Resources.Extensions
    Assembly Version: 5.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/leoun/Downloads/pkNX-master/pkNX-master/pkNX.WinForms/bin/Release/net461/pkNX.exe
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.1
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/leoun/Downloads/pkNX-master/pkNX-master/pkNX.WinForms/bin/Release/net461/pkNX.exe
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 4.0.6.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/leoun/Downloads/pkNX-master/pkNX-master/pkNX.WinForms/bin/Release/net461/pkNX.exe
----------------------------------------
FlatSharp
    Assembly Version: 5.7.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/leoun/Downloads/pkNX-master/pkNX-master/pkNX.WinForms/bin/Release/net461/pkNX.exe
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 4.1.4.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/leoun/Downloads/pkNX-master/pkNX-master/pkNX.WinForms/bin/Release/net461/pkNX.exe
----------------------------------------
FlatSharp.Runtime
    Assembly Version: 5.7.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/leoun/Downloads/pkNX-master/pkNX-master/pkNX.WinForms/bin/Release/net461/pkNX.exe
----------------------------------------
System.Collections.Immutable
    Assembly Version: 5.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/leoun/Downloads/pkNX-master/pkNX-master/pkNX.WinForms/bin/Release/net461/pkNX.exe
----------------------------------------
pkNX.Game
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/leoun/Downloads/pkNX-master/pkNX-master/pkNX.WinForms/bin/Release/net461/pkNX.exe
----------------------------------------
Microsoft.CodeAnalysis
    Assembly Version: 3.8.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/leoun/Downloads/pkNX-master/pkNX-master/pkNX.WinForms/bin/Release/net461/pkNX.exe
----------------------------------------
Microsoft.CodeAnalysis.CSharp
    Assembly Version: 3.8.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/leoun/Downloads/pkNX-master/pkNX-master/pkNX.WinForms/bin/Release/net461/pkNX.exe
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.2.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/leoun/Downloads/pkNX-master/pkNX-master/pkNX.WinForms/bin/Release/net461/pkNX.exe
----------------------------------------
pkNX.Containers
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/leoun/Downloads/pkNX-master/pkNX-master/pkNX.WinForms/bin/Release/net461/pkNX.exe
----------------------------------------
LZ4
    Assembly Version: 1.0.15.93
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/leoun/Downloads/pkNX-master/pkNX-master/pkNX.WinForms/bin/Release/net461/pkNX.exe
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 5.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/leoun/Downloads/pkNX-master/pkNX-master/pkNX.WinForms/bin/Release/net461/pkNX.exe
----------------------------------------
LZ4mm
    Assembly Version: 1.0.15.93
    Win32 Version: 1.0.15.93
    CodeBase: file:///C:/Users/leoun/AppData/Local/Temp/f82a68ada1d833f8838dd859bcb27a61/44b09ced47d1340e4b5af5cc6f2fc8b2.dll
----------------------------------------
LZ4cc
    Assembly Version: 1.0.15.93
    Win32 Version: 1.0.15.93
    CodeBase: file:///C:/Users/leoun/AppData/Local/Temp/f82a68ada1d833f8838dd859bcb27a61/bed5714f0a00711677483c138938e914.dll
----------------------------------------
System.Collections
    Assembly Version: 4.0.11.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/leoun/Downloads/pkNX-master/pkNX-master/pkNX.WinForms/bin/Release/net461/pkNX.exe
----------------------------------------
LZ4pn
    Assembly Version: 1.0.15.93
    Win32 Version: 1.0.15.93
    CodeBase: file:///C:/Users/leoun/AppData/Local/Temp/f82a68ada1d833f8838dd859bcb27a61/50495300240756128a79c0c0850f98e5.dll
----------------------------------------
pkNX.Sprites
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/leoun/Downloads/pkNX-master/pkNX-master/pkNX.WinForms/bin/Release/net461/pkNX.exe
----------------------------------------
pkNX.Randomization
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/leoun/Downloads/pkNX-master/pkNX-master/pkNX.WinForms/bin/Release/net461/pkNX.exe
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.`
```

**Comment by kwsch** [comment]
Did you build pkNX yourself or are you using the pipeline/forum?

I'll need to check if the pipeline merged exe has the new flatbuffer dll dependency included...

**Comment by TaskManager06** [comment]
I downloaded the one that already was a exe.

**Comment by kwsch** [comment]
Works fine from the latest pipeline.

Looking at your file paths, that's not what the download zip should look like. Please re-download and extract the entire zip to an empty folder.
