### ISSUE TITLE
Error when opening game file

### ISSUE THREAD

**Issue by masterkurisu** [kwsch/pkNX#85]
I'm getting this error when trying to open my dumped Pokemon Sword file. 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at pkNX.Structures.PersonalTable.SplitBytes(Byte[] data, Int32 size)
   at pkNX.Structures.PersonalTable..ctor(Byte[] data, GameVersion format)
   at pkNX.Game.GameManagerSWSH.Initialize()
   at pkNX.Game.GameManager..ctor(GameLocation rom, Int32 language)
   at pkNX.Game.GameManagerSWSH..ctor(GameLocation rom, Int32 language)
   at pkNX.Game.GameManager.GetManager(GameLocation loc, Int32 language)
   at pkNX.WinForms.Controls.EditorBase.GetEditor(String loc, Int32 language) in E:\Switch\PKHexSwitch\Raid dens\pkNX repo\pkNX.WinForms\MainEditor\EditorProvider.cs:line 63
   at pkNX.WinForms.Main.OpenFolder(String path) in E:\Switch\PKHexSwitch\Raid dens\pkNX repo\pkNX.WinForms\Main.cs:line 129
   at pkNX.WinForms.Main.OpenPath(String path) in E:\Switch\PKHexSwitch\Raid dens\pkNX repo\pkNX.WinForms\Main.cs:line 109
   at pkNX.WinForms.Main.Menu_Open_Click(Object sender, EventArgs e) in E:\Switch\PKHexSwitch\Raid dens\pkNX repo\pkNX.WinForms\Main.cs:line 62
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
pkNX
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///E:/Switch/PKHexSwitch/Raid%20dens/pkNX%20repo/pkNX.WinForms/bin/Debug/pkNX.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
pkNX.Structures
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///E:/Switch/PKHexSwitch/Raid%20dens/pkNX%20repo/pkNX.WinForms/bin/Debug/pkNX.exe
----------------------------------------
pkNX.Game
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///E:/Switch/PKHexSwitch/Raid%20dens/pkNX%20repo/pkNX.WinForms/bin/Debug/pkNX.exe
----------------------------------------
pkNX.Containers
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///E:/Switch/PKHexSwitch/Raid%20dens/pkNX%20repo/pkNX.WinForms/bin/Debug/pkNX.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by sora10pls** [comment]
Per the readme:
> **For Sword and Shield, pkNX operates under the assumption that your dumped ROM includes the Ver. 1.2.0 patch.**

SWSH Personal Data entries changed in size from `0xA8` to `0xB0` -- dump the latest patch and load that into the program.

**Comment by Bemvivo** [comment]
**i have the same issue and ive already dump the game with the new update**

**Comment by xCayde-6** [comment]
I'm having the same issue aswell, even with version 1.2.0. Have done multiple dumps and still nothing.
